language: java
sudo: false
script: mvn clean package
notifications:
  email:
    recipients:
      - t.incho52@hotmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always